### PR TITLE
initial revokeToken implementation

### PR DESCRIPTION
**Pull request by mohitpubnub**
feat: Added revokeToken feature.

Added support for Revoke Token feature.

### CODE REVIEW

**Review by are — APPROVED** [review]

**Comment by are** [comment]
@client-engineering-bot release as v4.1.0

**Review by raipubnub — APPROVED** [review]
LGTM!

**Review by techwritermat — APPROVED** [review]

**Comment by parfeon** [comment]
@are monorepos require to specify product name like this:

> @client-engineering-bot release dart as v4.1.0

**Comment by are** [comment]
@parfeon my bad... Forgot about it! Sorry :(

**Pull request merged**
