### PR TITLE
Make v4.0.0 stable release

### LINKED ISSUE #46: PubNubException: Can not decrypt the message payload.
I got this error when listening to messages stream.

I found out that the encrypted message sent out is not tally with the message received (as shown in the screenshot below) when I try to dig into the PubNub code.
image

### LINKED ISSUE #50: pubnub error "Signature does not match"
when i try code:
---------------
```
 PubNub pubNub = PubNub(
                  defaultKeyset: Keyset(
                    publishKey: 'myPublishKey',
                    subscribeKey: 'mySubscribeKey',
                    secretKey: 'mySecretKey',
                  ),
                );
final createUser = await pubNub.objects.setUUIDMetadata(
                    UuidMetadataInput(
                      name: 'userName',
                      email: 'email@gmail.com',
                    ),
                    uuid: 'uuild');
```
error:
------------

`Exception has occurred.
PubNubException (PubNubException: 403 error: Signature does not match
#0      new PubNubException (package:pubnub/src/core/exceptions.dart:9:29)
#1      getExceptionFromDefaultResult (package:pubnub/src/dx/_utils/exceptions.dart:41:10)
#2      getExceptionFromAny (package:pubnub/src/dx/_utils/exceptions.dart:7:12)
#3      _defaultFlow (package:pubnub/src/dx/_utils/default_flow.dart:82:11)
<asynchronous suspension>
#4      Fiber.run (package:pubnub/src/core/supervisor/fiber.dart:37:20)
<asynchronous suspension>
#5      defaultFlow (package:pubnub/src/dx/_utils/default_flow.dart:27:3)
<asynchronous suspension>
#6      _MyHomePageState.build.<anonymous closure> (package:flutter_pubnub_chat/main.dart:116:36)
<asynchronous suspension>
 )`

### LINKED ISSUE #62: Pool resources not released on time?
I had to increase pool resources from 10 to 100 to be able to send messages. With the default 10 resources limit `.publish()` kept waiting and waiting for resources to release forever.

SDK version 4.0.0.beta-1

### LINKED ISSUE #63: Can't recover from unhandled exceptions in the subscribe loop
We're using the 4.0 beta. 

We've been fielding complaints from our users that they are missing incoming messages. We have error reports for various exceptions, most of which look like they would probably come right if we reconnect.

What we found confusing was that we weren't able to fix the problem by taking actions in our code to do that. Specifically, we have tried both calling reconnect(), and cancelling the subscription and all stream listeners and then subscribing again.

When this happens, I see the `State has been updated.` log and `Resuming subscription.`, but never see another `Starting new loop iteration.`.

I've been debugging the library code and I believe that the problem is that if no resolution is found by the strategy, then SubscribeLoop's `Stream<Envelope> _loop() async*` will rethrow:

```dart
        if (resolutions == null) {
          _logger.silly('No resolutions found.');
          rethrow;
        }
```

And the same if the resolution is Fail, though that isn't really central to my concern since we don't want that resolution anyway and so have a retry policy (which I see in the code retries infinitely for a subscribe fiber - fine by me):

```dart
          if (resolution is FailResolution) {
            rethrow;
```

Anyway, throwing/rethrowing out of _loop causes an addError on the stream, which is how we know to try our reconnect and resubscribe.

But _loop() will never re-enter its `while (true)` loop. If I understand the language spec correctly, the method is called when the stream is listen()ed on, which only happens in the SubscribeLoop constructor:

```dart
    var loopStream = _loop();

    loopStream.listen((envelope) {
      _messagesController.add(envelope);
    }, onError: (exception) {
      _messagesController.addError(exception);
    });
```

And even if we wanted to, we couldn't reenter without recreating the stream, because the stream is closed when the method exits.

But it looks to me like the manager class only ever creates a SubscribeLoop in its constructor:

```dart
  Manager(Core core, this.keyset) {
    _loop = SubscribeLoop(core, SubscribeLoopState(keyset));
  }
```

Therefore, after any exception thrown/rethrown by _loop(), there will never again be any events emitted on any subscription stream?

So if I have the above stuff right, I think any time there is an unhandled exception, subscriptions become permanently unusable for the whole PubNub instance, but subscribe() silently stops working rather than raising an error?

### LINKED ISSUE #64: Weird 'subscribe failed' exceptions
We're using the 4.0 beta. We're seeing some weird generic _Exception exception error reports with the message `subscribe failed` and no backtrace.

~They get wrapped in a `RequestOtherException` which _does_ have a backtrace, but it's just RequestHandler.response (package:pubnub/src/networking/request_handler/io.dart:139).~ Turns this bit was inapplicable, that was Sentry grouping too many errors together. We have no backtrace that I can see.

I can't find this error actually get thrown anywhere (not in the pubnub library nor our app). But, there is this inside SubscribeLoop's _loop():

```
        if (diagnostic == null) {
          _logger.warning('No diagnostics found.');

          if (!_whenStarts.isCompleted) {
            _whenStarts.completeError(Exception('subscribe failed'));
          }
          rethrow;
        }
```

(Coincidentally, this is the same method involved in #63 which @are is looking into)

Since that Exception passed to completeError isn't actually _thrown_, I guess that would explain the lack of a backtrace?

But even if this is the source of the exception, I still don't understand:
* Under what conditions the subscribe loop goes into this !isCompleted case when an exception is caught - actually, it looks to me like it will run this completeError *every* time, because _whenStarts is reset to a new Completer as soon as it is completed in the code above
* How this error completion gets thrown later. We don't have any references to whenStarts or _whenStarts, and although the library itself has some delegations to expose it, I don't see anything in the library actually using it.

It's almost as if the exception that is created but not raised becomes the exception that `rethrows` throws? But that feels hard to believe!

### LINKED ISSUE #65: Handle more socket exceptions
As per #63 unhandled exceptions are a pretty significant problem right now, so we've been trying to identify and add diagnostics for all the errors we see in production. It's common for us because our app is used for deliveries and drivers regularly experience temporary comms problems as they go around, particularly in less populated hilly areas.

Happily the library allows us to extend the built-in detection. But, I think everyone is going to have the same problems as us, so I'd like to suggest a much broader set of diagnostics.

Hoping that you would upstream them later, we started out by extending the list of exceptions using exactly the same exact-match methodology as the library itself, a bit like these ones:

```
  RegExp(r'^SocketException: OS Error: Software caused connection abort, errno = 103, address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r'^SocketException: Connection failed \(OS Error: Host is down, errno = 64\), address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
```

This looked like this:

```
  RegExp(r'^SocketException: Write failed \(OS Error: Software caused connection abort, errno = 103\), address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r'^SocketException: Read failed \(OS Error: Software caused connection abort, errno = 103\), address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r'^SocketException: OS Error: Connection reset by peer, errno = 104, address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r'^SocketException: OS Error: Connection refused, errno = 61, address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r'^SocketException: OS Error: No route to host, errno = 113, address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  // see https://developer.apple.com/library/archive/technotes/tn2277/_index.html#//apple_ref/doc/uid/DTS40010841-CH1-SUBSECTION3 for this one - this is expected unlike a normal Unix EBADF:
  RegExp(r'^SocketException: OS Error: Bad file descriptor, errno = 9, address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r'^SocketException: OS Error: Connection timed out, errno = 110, address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r'^SocketException: Connection failed \(OS Error: Network is unreachable, errno = 101\), address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r"^SocketException: Failed host lookup: '([a-zA-Z0-9\-\.]+)' \(OS Error: nodename nor servname provided, or not known, errno = 8\)$"): (match) =>
      HostLookupFailedDiagnostic(match?.group(1)),
  RegExp(r"^SocketException: Failed host lookup: '([a-zA-Z0-9\-\.]+)' \(OS Error: No address associated with hostname, errno = 7\)$"): (match) =>
      HostLookupFailedDiagnostic(match?.group(1)),
  RegExp(r'^SocketException: OS Error: Operation timed out'): (match) => UnknownHttpExceptionDiagnostic(),
  RegExp(r'^HttpException: Write failed, uri ='): (match) =>
      UnknownHttpExceptionDiagnostic(),
  RegExp(r'^HttpException: Connection closed before full header was received, uri ='): (match) =>
      UnknownHttpExceptionDiagnostic(),
  RegExp(r'^HandshakeException: Connection terminated during handshake$'): (match) =>
      UnknownHttpExceptionDiagnostic(),
  RegExp(r'^HandshakeException: Handshake error in client'): (match) =>
      UnknownHttpExceptionDiagnostic(),
```

Already you can see the list is getting pretty large. But in prod we found that we were getting many of the same errors all over again - except that they had different OS errno codes.

This is because Android runs on a Linux-derived kernel and iOS on a Darwin-derived kernel. These two have both used the BSD error constants but *the values are different*. So I started out by adding the two variants:

```
  RegExp(r'^SocketException: Write failed \(OS Error: Software caused connection abort, errno = (103|53)\), address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
```

But in general, these are compile-time constants, but are not portable across operating systems. IMHO it makes no sense to hardcode them. I think there's no need to bring this in, so I suggest moving to this style:

```
  RegExp(r'^SocketException: Write failed \(OS Error: Software caused connection abort, errno = [0-9]+\), address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r'^SocketException: Read failed \(OS Error: Software caused connection abort, errno = [0-9]+\), address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r'^SocketException: OS Error: Connection reset by peer, errno = [0-9]+, address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r'^SocketException: OS Error: Connection refused, errno = [0-9]+, address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r'^SocketException: OS Error: No route to host, errno = [0-9]+, address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  // see https://developer.apple.com/library/archive/technotes/tn2277/_index.html#//apple_ref/doc/uid/DTS40010841-CH1-SUBSECTION3 for this one - this is expected unlike a normal Unix EBADF:
  RegExp(r'^SocketException: OS Error: Bad file descriptor, errno = 9, address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r'^SocketException: OS Error: Connection timed out, errno = [0-9]+, address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r'^SocketException: Connection failed \(OS Error: Network is unreachable, errno = [0-9]+\), address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r"^SocketException: Failed host lookup: '([a-zA-Z0-9\-\.]+)' \(OS Error: nodename nor servname provided, or not known, errno = 8\)$"): (match) =>
      HostLookupFailedDiagnostic(match?.group(1)),
  RegExp(r"^SocketException: Failed host lookup: '([a-zA-Z0-9\-\.]+)' \(OS Error: No address associated with hostname, errno = 7\)$"): (match) =>
      HostLookupFailedDiagnostic(match?.group(1)),
  RegExp(r'^SocketException: OS Error: Operation timed out'): (match) => UnknownHttpExceptionDiagnostic(),
  RegExp(r'^HttpException: Write failed, uri ='): (match) =>
      UnknownHttpExceptionDiagnostic(),
  RegExp(r'^HttpException: Connection closed before full header was received, uri ='): (match) =>
      UnknownHttpExceptionDiagnostic(),
  RegExp(r'^HandshakeException: Connection terminated during handshake$'): (match) =>
      UnknownHttpExceptionDiagnostic(),
  RegExp(r'^HandshakeException: Handshake error in client'): (match) =>
      UnknownHttpExceptionDiagnostic(),
```

But although incrementally better, I think this is still an unsustainable approach, for a few reasons:
1. Looking at the list of OS errors you can get from socket functions, there's still a bunch that I haven't handled in the list, which I assume are rarer but still possible
2. I'm still seeing some exceptions in production that look like they're the same underlying error, but they have a different string at the start, for example "RequestOtherException: *request failed* (SocketException: OS Error: Network is unreachable, errno = 101, address = ps.pndsn.com, port = 33008)"
3. Even some of those errors that in C would clearly indicate a programming error rather than a network fault, such as EBADF, are actually used for normal error conditions now (iOS uses them for connections aborted because the application was backgrounded).
4. I suspect that if the app is running in a non-C locale, the error messages will be localised. I haven't tested whether the Android userland, iOS userland, or Dart VM themselves actually do run the app in non-C locales (and we won't see it in prod for our app as our drivers are all using English), but it is certainly a problem in C programs in general - you have to use the error codes rather than rely on the messages.

So, long story short, I don't think it makes sense to keep playing whack-a-mole and coding in these detailed exception strings.

Is there any reason not to just capture all SocketException, HttpException, and HandshakeException errors and diagnose them all as temporary?

Something like this:

```
  RegExp(r'^SocketException: .* address = ([a-zA-Z0-9\-\.]+), port = ([0-9]+)$'):
      (match) => HostIsDownDiagnostic(
          match?.group(1), int.tryParse(match?.group(2) ?? '')),
  RegExp(r"^SocketException: Failed host lookup: '([a-zA-Z0-9\-\.]+)'"):
      (match) => HostLookupFailedDiagnostic(match?.group(1)),
  RegExp(r'^SocketException:'): (match) => UnknownHttpExceptionDiagnostic(),
  RegExp(r'^HttpException:'): (match) => UnknownHttpExceptionDiagnostic(),
  RegExp(r'^HandshakeException:'): (match) => UnknownHttpExceptionDiagnostic(),
```

Perhaps even use normal exception class tests instead of string matching?

### PR DESCRIPTION
**Pull request by are**
feat: add PAM v3 support

Adds PAM v3 support with `grantToken` and `setToken`.

fix: change subscribe loop to no longer throw

Subscribe loop no longer throws on unrecoverable failure, instead waits for restart.

Closes #63

feat: add restore method to subscription

After subscribe loop fails, call restore to restart it.

fix: add more specific diagnostics

Adds more diagnostics for network module.

Closes #65

fix: change whenStarts to stream

WhenStarts future no longer throws and is now based on a stream.

Closes #64

fix: release resources on failure

Networking should now release all resources after a failure.

Closes #62

fix: Signature mismatch issue.

Fixes issue of Signature mismatch with PAM enabled keysets.

Closes #50

fix: Message decryption failure in subscribe.

Fixes issue of message decryption with subscription.

Closes #46

### CODE REVIEW

**Review by raipubnub — APPROVED** [review]
LGTM!

**Review by mohitpubnub — APPROVED** [review]
LGTM

**Comment by parfeon** [comment]
Let me check it once again :D

**Comment by mohitpubnub** [comment]
@are Does updated PR comment covers all the changes appropriately.?

**Comment by are** [comment]
> @are Does updated PR comment cover all the changes appropriately!!?

Yes! Excellent work on this!

**Review by mohitpubnub — APPROVED** [review]

**Comment by parfeon** [comment]
@client-engineering-bot publish dart as v4.0.0

**Comment by parfeon** [comment]
@client-engineering-bot release dart as v4.0.0

**Review by mohitpubnub — APPROVED** [review]

**Review by techwritermat — APPROVED** [review]
.md files look ok

**Review by mohitpubnub — APPROVED** [review]

**Review by techwritermat — APPROVED** [review]

**Pull request merged**
